name: Build and Push Docker Image to ECR

# on:
#   push:
#     branches: [ "main" ]

on:
  workflow_dispatch: # Der Workflow wird nur manuell ausgeführt


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      IMAGE_NAME: live-chat-app
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Image to ECR
        run: |
          # Baue das Docker Image 
          docker build -t $IMAGE_NAME ./backend
          # Taggen des Images für ECR
          docker tag $IMAGE_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
          # Push to ECR
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:latest
