name: Build and Deploy Frontend to S3

# on:
#   push:
#     branches: [ "main" ]

on:
  workflow_dispatch: # Der Workflow wird nur manuell ausgeführt
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Passe die Node.js-Version an dein Projekt an

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend # Gehe ins Frontend-Verzeichnis

      - name: Build the frontend
        run: npm run build
        working-directory: ./frontend # Baue das Projekt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/build s3://$S3_BUCKET_NAME --delete
        env:
          AWS_REGION: eu-central-1
